### ISSUE TITLE
genesis_plus_gx core is black screen

### ISSUE THREAD

**Issue by taskgolden** [linuxserver/libretrojs#2]
According the example, I use the following html for genesis_plus_gx core, it will show black screen, other core didn't have this problem

```html
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <title>cthcj</title>    
    </head>
<body>
    <button onclick="load()">Load Game</button>
    <div id="game"></div>
    <script type="text/javascript">
        EJS_player = '#game';
        EJS_gameUrl = 'Contra_The_Hard_Corps_J.bin';
        EJS_core = 'genesis_plus_gx';
        function load() {
          var script = document.createElement('script');
          script.src = 'js/libretro.js'
          document.getElementsByTagName('head')[0].appendChild(script);
        }
    </script>
</body>
</html>
```

**Comment by thomasgoldstein** [comment]
I had the same problem but found a workaround: if you change your ROM file extension to .smd or .md, then it'll work. Only the .bin extension triggers this issue.

**Comment by thomasgoldstein** [comment]
This comment explains why it does not work: https://github.com/linuxserver/emulatorjs/issues/49#issuecomment-1130114686

> I would zip them, unfortunately the logic as it exists assumes a .bin file is a cd image and looks for it's accompanying cue file.

I believe it's not a bug. And if it was actually one, then it'd be an emulatorjs issue, not an issue with this repo here.

**Comment by thelamer** [comment]
Sorry I actually forgot about this repo and the updates are run manually to pickup new version upstream. 
Yes always use zips for cartridge dumps and chd for CD dumps. The whole system really has been designed around that concept. Bin/Cue has its own logic which could likely use some improvement but it is what it is right now.
